using System;

namespace OpenDentBusiness {

	[Serializable]
	[ODTable(IsMissingInGeneral=true,CrudExcludePrefC=true)]
	public class WebChatMessage:ODTable {

		///<summary>Primary key.</summary>
		[ODTableColumn(PrimaryKey=true)]
		public long WebChatMessageNum;
		///<summary>FK to webchatsession.WebChatSessionNum</summary>
		public long WebChatSessionNum;
		///<summary>Blank when MessageType is System.</summary>
		public string UserName;
		[ODTableColumn(SpecialType=CrudSpecialColType.TimeStamp)]
		public DateTime DateT;
		///<summary>The chat message content.</summary>
		public string MessageText;
		///<summary>Who created the message.</summary>
		public WebChatMessageType MessageType;

	}

	///<summary>Describes where the message was generated from.</summary>
	public enum WebChatMessageType {
		///<summary>Automatically generated by the chat system.</summary>
		System,
		///<summary>A special system message.  Once a message with this type is added to a session, the session is frozen forever.</summary>
		EndSession,
		///<summary>Message manually typed by a technician.</summary>
		Technician,
		///<summary>Message manually typed by the customer.</summary>
		Customer,
	}

}