//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDental.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenDental.Translation.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy.
        /// </summary>
        public static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this allergy?.
        /// </summary>
        public static string AllergyConfirmDelete {
            get {
                return ResourceManager.GetString("AllergyConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy Definition.
        /// </summary>
        public static string AllergyDef {
            get {
                return ResourceManager.GetString("AllergyDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete allergies in use..
        /// </summary>
        public static string AllergyDefCannotDeleteInUse {
            get {
                return ResourceManager.GetString("AllergyDefCannotDeleteInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this allergy definition?.
        /// </summary>
        public static string AllergyDefConfirmDelete {
            get {
                return ResourceManager.GetString("AllergyDefConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one code is allowed per allergy def..
        /// </summary>
        public static string AllergyOnlyOneUniiCodePerAllergyAllowed {
            get {
                return ResourceManager.GetString("AllergyOnlyOneUniiCodePerAllergyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one allergy..
        /// </summary>
        public static string AllergySelectAtLeastOne {
            get {
                return ResourceManager.GetString("AllergySelectAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy Setup.
        /// </summary>
        public static string AllergySetup {
            get {
                return ResourceManager.GetString("AllergySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNII code contains invalid characters: {0}.
        /// </summary>
        public static string AllergyUniiCodeContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("AllergyUniiCodeContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNII code must be 10 characters in length..
        /// </summary>
        public static string AllergyUniiCodeMustBe10Characters {
            get {
                return ResourceManager.GetString("AllergyUniiCodeMustBe10Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Suppliers.
        /// </summary>
        public static string AllSuppliers {
            get {
                return ResourceManager.GetString("AllSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is in progress on workstation &apos;{0}&apos;.
        ///
        ///Not allowed to start Softlex while an update is in progress.
        ///Please wait and click &apos;Try Again&apos;..
        /// </summary>
        public static string AnUpdateIsInProgressOnWorkstation {
            get {
                return ResourceManager.GetString("AnUpdateIsInProgressOnWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autograph.
        /// </summary>
        public static string Autograph {
            get {
                return ResourceManager.GetString("Autograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autograph cannot be blank..
        /// </summary>
        public static string AutographCannotBeBlank {
            get {
                return ResourceManager.GetString("AutographCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not available, or there is an error in the command line options..
        /// </summary>
        public static string BridgeExecutableNotAvailable {
            get {
                return ResourceManager.GetString("BridgeExecutableNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        public static string BridgeExecutableNotFound {
            get {
                return ResourceManager.GetString("BridgeExecutableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the default mail address..
        /// </summary>
        public static string CannotDeleteDefaultMailAddress {
            get {
                return ResourceManager.GetString("CannotDeleteDefaultMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete user group that is set as the default user group..
        /// </summary>
        public static string CannotDeleteDefaultUserGroup {
            get {
                return ResourceManager.GetString("CannotDeleteDefaultUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the e-mail address because it is used by clinic {0}..
        /// </summary>
        public static string CannotDeleteMailAddressInUseByClinic {
            get {
                return ResourceManager.GetString("CannotDeleteMailAddressInUseByClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are the person who started the update and you wish to override this message because an update is not in progress, click &apos;Override&apos;..
        /// </summary>
        public static string ClickOverrideToOverrideUpdateMessage {
            get {
                return ResourceManager.GetString("ClickOverrideToOverrideUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string ColumnAmount {
            get {
                return ResourceManager.GetString("ColumnAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string ColumnBalance {
            get {
                return ResourceManager.GetString("ColumnBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Number.
        /// </summary>
        public static string ColumnBankNumber {
            get {
                return ResourceManager.GetString("ColumnBankNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog #.
        /// </summary>
        public static string ColumnCatalogNumber {
            get {
                return ResourceManager.GetString("ColumnCatalogNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ColumnCategory {
            get {
                return ResourceManager.GetString("ColumnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string ColumnColumn {
            get {
                return ResourceManager.GetString("ColumnColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        public static string ColumnColumnName {
            get {
                return ResourceManager.GetString("ColumnColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string ColumnCost {
            get {
                return ResourceManager.GetString("ColumnCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string ColumnCustomerID {
            get {
                return ResourceManager.GetString("ColumnCustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ColumnDate {
            get {
                return ResourceManager.GetString("ColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string ColumnDateAdded {
            get {
                return ResourceManager.GetString("ColumnDateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Placed.
        /// </summary>
        public static string ColumnDatePlaced {
            get {
                return ResourceManager.GetString("ColumnDatePlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Purchased.
        /// </summary>
        public static string ColumnDatePurchased {
            get {
                return ResourceManager.GetString("ColumnDatePurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Received.
        /// </summary>
        public static string ColumnDateReceived {
            get {
                return ResourceManager.GetString("ColumnDateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Sold.
        /// </summary>
        public static string ColumnDateSold {
            get {
                return ResourceManager.GetString("ColumnDateSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        public static string ColumnDateTime {
            get {
                return ResourceManager.GetString("ColumnDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ColumnDefault {
            get {
                return ResourceManager.GetString("ColumnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        public static string ColumnDel {
            get {
                return ResourceManager.GetString("ColumnDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ColumnDescription {
            get {
                return ResourceManager.GetString("ColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ColumnEnabled {
            get {
                return ResourceManager.GetString("ColumnEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string ColumnEndDate {
            get {
                return ResourceManager.GetString("ColumnEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est Value.
        /// </summary>
        public static string ColumnEstValue {
            get {
                return ResourceManager.GetString("ColumnEstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string ColumnFrom {
            get {
                return ResourceManager.GetString("ColumnFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string ColumnHidden {
            get {
                return ResourceManager.GetString("ColumnHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string ColumnInactive {
            get {
                return ResourceManager.GetString("ColumnInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text.
        /// </summary>
        public static string ColumnInputText {
            get {
                return ResourceManager.GetString("ColumnInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ColumnLocation {
            get {
                return ResourceManager.GetString("ColumnLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Text.
        /// </summary>
        public static string ColumnLogText {
            get {
                return ResourceManager.GetString("ColumnLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Type.
        /// </summary>
        public static string ColumnMessageType {
            get {
                return ResourceManager.GetString("ColumnMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string ColumnNote {
            get {
                return ResourceManager.GetString("ColumnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Hand Qty.
        /// </summary>
        public static string ColumnOnHandQty {
            get {
                return ResourceManager.GetString("ColumnOnHandQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        public static string ColumnPageTitle {
            get {
                return ResourceManager.GetString("ColumnPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ColumnPassword {
            get {
                return ResourceManager.GetString("ColumnPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string ColumnPatient {
            get {
                return ResourceManager.GetString("ColumnPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paycheck Date.
        /// </summary>
        public static string ColumnPaycheckDate {
            get {
                return ResourceManager.GetString("ColumnPaycheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string ColumnPermission {
            get {
                return ResourceManager.GetString("ColumnPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ColumnPhone {
            get {
                return ResourceManager.GetString("ColumnPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed By.
        /// </summary>
        public static string ColumnPlacedBy {
            get {
                return ResourceManager.GetString("ColumnPlacedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ColumnPrice {
            get {
                return ResourceManager.GetString("ColumnPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price/Unit.
        /// </summary>
        public static string ColumnPricePerUnit {
            get {
                return ResourceManager.GetString("ColumnPricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string ColumnQty {
            get {
                return ResourceManager.GetString("ColumnQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string ColumnSaved {
            get {
                return ResourceManager.GetString("ColumnSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string ColumnSender {
            get {
                return ResourceManager.GetString("ColumnSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string ColumnSerialNumber {
            get {
                return ResourceManager.GetString("ColumnSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string ColumnShipping {
            get {
                return ResourceManager.GetString("ColumnShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string ColumnStartDate {
            get {
                return ResourceManager.GetString("ColumnStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ColumnStatus {
            get {
                return ResourceManager.GetString("ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Qty.
        /// </summary>
        public static string ColumnStockQty {
            get {
                return ResourceManager.GetString("ColumnStockQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string ColumnSubject {
            get {
                return ResourceManager.GetString("ColumnSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string ColumnSubtotal {
            get {
                return ResourceManager.GetString("ColumnSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string ColumnSupplier {
            get {
                return ResourceManager.GetString("ColumnSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ColumnTitle {
            get {
                return ResourceManager.GetString("ColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ColumnType {
            get {
                return ResourceManager.GetString("ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ColumnUser {
            get {
                return ResourceManager.GetString("ColumnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string ColumnUserName {
            get {
                return ResourceManager.GetString("ColumnUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ColumnValue {
            get {
                return ResourceManager.GetString("ColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string ColumnWebsite {
            get {
                return ResourceManager.GetString("ColumnWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ColumnWidth {
            get {
                return ResourceManager.GetString("ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yr.
        /// </summary>
        public static string ColumnYr {
            get {
                return ResourceManager.GetString("ColumnYr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete this?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful..
        /// </summary>
        public static string ConnectionSuccessful {
            get {
                return ResourceManager.GetString("ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password incorrect..
        /// </summary>
        public static string CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is in the future. Continue anyway?.
        /// </summary>
        public static string DateIsInFutureContinueAnyway {
            get {
                return ResourceManager.GetString("DateIsInFutureContinueAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        public static string DateRangeFromTo {
            get {
                return ResourceManager.GetString("DateRangeFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be blank..
        /// </summary>
        public static string DescriptionCannotBeBlank {
            get {
                return ResourceManager.GetString("DescriptionCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show me this message again..
        /// </summary>
        public static string DoNotShowThisMessageAgain {
            get {
                return ResourceManager.GetString("DoNotShowThisMessageAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name..
        /// </summary>
        public static string EnterAName {
            get {
                return ResourceManager.GetString("EnterAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a valid date..
        /// </summary>
        public static string EnterAValidDate {
            get {
                return ResourceManager.GetString("EnterAValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter or select a valid time..
        /// </summary>
        public static string EnterOrSelectAValidDate {
            get {
                return ResourceManager.GetString("EnterOrSelectAValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment List.
        /// </summary>
        public static string EquipmentList {
            get {
                return ResourceManager.GetString("EquipmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number already in use. Please enter another..
        /// </summary>
        public static string EquipmentSerialNumberIsAlreadInUse {
            get {
                return ResourceManager.GetString("EquipmentSerialNumberIsAlreadInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates..
        /// </summary>
        public static string ErrorCheckingForUpdates {
            get {
                return ResourceManager.GetString("ErrorCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox check interval must be between 1 and 60 inclusive..
        /// </summary>
        public static string InboxCheckIntervalMustBeBetween1And60 {
            get {
                return ResourceManager.GetString("InboxCheckIntervalMustBeBetween1And60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date..
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid incoming port number..
        /// </summary>
        public static string InvalidIncomingPortNumber {
            get {
                return ResourceManager.GetString("InvalidIncomingPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid outgoing port number..
        /// </summary>
        public static string InvalidOutgoingPortNumber {
            get {
                return ResourceManager.GetString("InvalidOutgoingPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registration key..
        /// </summary>
        public static string InvalidRegistrationKey {
            get {
                return ResourceManager.GetString("InvalidRegistrationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registration key format..
        /// </summary>
        public static string InvalidRegistrationKeyFormat {
            get {
                return ResourceManager.GetString("InvalidRegistrationKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items added to order successfully.
        /// </summary>
        public static string ItemsAddedToOrderSuccessfully {
            get {
                return ResourceManager.GetString("ItemsAddedToOrderSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Saved.
        /// </summary>
        public static string lang_last_saved {
            get {
                return ResourceManager.GetString("lang_last_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string lang_user {
            get {
                return ResourceManager.GetString("lang_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has logged on.
        /// </summary>
        public static string lang_user_has_logged_on {
            get {
                return ResourceManager.GetString("lang_user_has_logged_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to log off?.
        /// </summary>
        public static string LogOffConfirmation {
            get {
                return ResourceManager.GetString("LogOffConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An mail address already exists for {0}..
        /// </summary>
        public static string MailAddressAlreadyExistsForUser {
            get {
                return ResourceManager.GetString("MailAddressAlreadyExistsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Search Filter.
        /// </summary>
        public static string NoSearchFilter {
            get {
                return ResourceManager.GetString("NoSearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supply categories have been created. Go to the supply inventory window, select categories, and enter at least one supply category first..
        /// </summary>
        public static string NoSupplyCategoriesHaveBeenCreated {
            get {
                return ResourceManager.GetString("NoSupplyCategoriesHaveBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to add a new order when there is already one pending. Please finish the other order instead..
        /// </summary>
        public static string NotAllowedToAddNewOrderWhenOneIsPending {
            get {
                return ResourceManager.GetString("NotAllowedToAddNewOrderWhenOneIsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to delete unless date is blank..
        /// </summary>
        public static string NotAllowedToDeleteUnlessDateIsBlank {
            get {
                return ResourceManager.GetString("NotAllowedToDeleteUnlessDateIsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Showing Hidden Items.
        /// </summary>
        public static string NotShowingHiddenItems {
            get {
                return ResourceManager.GetString("NotShowingHiddenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of days after pay period cannot be zero..
        /// </summary>
        public static string NumberOfDaysAfterPayPeriodCannotBeZero {
            get {
                return ResourceManager.GetString("NumberOfDaysAfterPayPeriodCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of payment periods to generate must be above 0..
        /// </summary>
        public static string NumberOfPayPeriodsMustBeAboveZero {
            get {
                return ResourceManager.GetString("NumberOfPayPeriodsMustBeAboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dental.
        /// </summary>
        public static string OpenDental {
            get {
                return ResourceManager.GetString("OpenDental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match and not be empty..
        /// </summary>
        public static string PasswordsMustMatchAndNotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordsMustMatchAndNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paycheck date cannot be on or before the end date of the pay period..
        /// </summary>
        public static string PaycheckDateCannotBeOnOrBeforeEndDate {
            get {
                return ResourceManager.GetString("PaycheckDateCannotBeOnOrBeforeEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Period.
        /// </summary>
        public static string PayPeriod {
            get {
                return ResourceManager.GetString("PayPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pay period overlaps with existing pay periods. Please fix this pay period first..
        /// </summary>
        public static string PayPeriodIsOverlapping {
            get {
                return ResourceManager.GetString("PayPeriodIsOverlapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Period Manager.
        /// </summary>
        public static string PayPeriodManager {
            get {
                return ResourceManager.GetString("PayPeriodManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay periods must be generated first..
        /// </summary>
        public static string PayPeriodsMustBeGeneratedFirst {
            get {
                return ResourceManager.GetString("PayPeriodsMustBeGeneratedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created pay periods that would overlap with existing pay periods. Please fix those pay periods first..
        /// </summary>
        public static string PayPeriodsWouldOverlap {
            get {
                return ResourceManager.GetString("PayPeriodsWouldOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Account.
        /// </summary>
        public static string PickAccount {
            get {
                return ResourceManager.GetString("PickAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Time.
        /// </summary>
        public static string PickTime {
            get {
                return ResourceManager.GetString("PickTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick User.
        /// </summary>
        public static string PickUser {
            get {
                return ResourceManager.GetString("PickUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Users.
        /// </summary>
        public static string PickUsers {
            get {
                return ResourceManager.GetString("PickUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a description..
        /// </summary>
        public static string PleaseEnterADescription {
            get {
                return ResourceManager.GetString("PleaseEnterADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid mail address..
        /// </summary>
        public static string PleaseEnterAValidMailAddress {
            get {
                return ResourceManager.GetString("PleaseEnterAValidMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date purchased..
        /// </summary>
        public static string PleaseEnterDatePurchased {
            get {
                return ResourceManager.GetString("PleaseEnterDatePurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the missing fields first..
        /// </summary>
        public static string PleaseFillInTheMissingFieldsFirst {
            get {
                return ResourceManager.GetString("PleaseFillInTheMissingFieldsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix data entry errors first..
        /// </summary>
        public static string PleaseFixDataEntryErrors {
            get {
                return ResourceManager.GetString("PleaseFixDataEntryErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick a user first..
        /// </summary>
        public static string PleasePickAUserFirst {
            get {
                return ResourceManager.GetString("PleasePickAUserFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an mail address..
        /// </summary>
        public static string PleaseSelectAMailAddress {
            get {
                return ResourceManager.GetString("PleaseSelectAMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an account first..
        /// </summary>
        public static string PleaseSelectAnAccountFirst {
            get {
                return ResourceManager.GetString("PleaseSelectAnAccountFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an email message..
        /// </summary>
        public static string PleaseSelectAnEmailMessage {
            get {
                return ResourceManager.GetString("PleaseSelectAnEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a patient first..
        /// </summary>
        public static string PleaseSelectAPatientFirst {
            get {
                return ResourceManager.GetString("PleaseSelectAPatientFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row first..
        /// </summary>
        public static string PleaseSelectARowFirst {
            get {
                return ResourceManager.GetString("PleaseSelectARowFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a supplier first..
        /// </summary>
        public static string PleaseSelectASupplierFirst {
            get {
                return ResourceManager.GetString("PleaseSelectASupplierFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a supplier from the list first..
        /// </summary>
        public static string PleaseSelectASupplierFromTheList {
            get {
                return ResourceManager.GetString("PleaseSelectASupplierFromTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a supply from the list first..
        /// </summary>
        public static string PleaseSelectASupplyFromTheList {
            get {
                return ResourceManager.GetString("PleaseSelectASupplyFromTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a supply order to add items to first..
        /// </summary>
        public static string PleaseSelectASupplyOrderToAddItemsTo {
            get {
                return ResourceManager.GetString("PleaseSelectASupplyOrderToAddItemsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user that does not have an inbox..
        /// </summary>
        public static string PleaseSelectAUserThatDoesNotHaveAnInbox {
            get {
                return ResourceManager.GetString("PleaseSelectAUserThatDoesNotHaveAnInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify some search criteria before searching..
        /// </summary>
        public static string PleaseSpecifySearchCriteriaBeforeSearching {
            get {
                return ResourceManager.GetString("PleaseSpecifySearchCriteriaBeforeSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem refreshing the Audit Trail with the current filters..
        /// </summary>
        public static string ProblemRefreshingAuditTrail {
            get {
                return ResourceManager.GetString("ProblemRefreshingAuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased.
        /// </summary>
        public static string Purchased {
            get {
                return ResourceManager.GetString("Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Enter Password.
        /// </summary>
        public static string ReEnterPassword {
            get {
                return ResourceManager.GetString("ReEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Key.
        /// </summary>
        public static string RegistrationKey {
            get {
                return ResourceManager.GetString("RegistrationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filter.
        /// </summary>
        public static string SearchFilter {
            get {
                return ResourceManager.GetString("SearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have finished setup..
        /// </summary>
        public static string SetupComplete {
            get {
                return ResourceManager.GetString("SetupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not finished setting this section up yet.
        ///{0}
        ///Click &apos;Skip&apos; if you do not wish to finish setting this section up at this time..
        /// </summary>
        public static string SetupStepIncomplete {
            get {
                return ResourceManager.GetString("SetupStepIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Setup.
        /// </summary>
        public static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping List.
        /// </summary>
        public static string ShoppingList {
            get {
                return ResourceManager.GetString("ShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Filtered.
        /// </summary>
        public static string ShowFiltered {
            get {
                return ResourceManager.GetString("ShowFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing Hidden Items.
        /// </summary>
        public static string ShowingHiddenItems {
            get {
                return ResourceManager.GetString("ShowingHiddenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        public static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start and end dates are required..
        /// </summary>
        public static string StartAndEndDatesRequired {
            get {
                return ResourceManager.GetString("StartAndEndDatesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be sure to stop the program on all other computers in the office before installing..
        /// </summary>
        public static string StopProgramOnAllComputersBeforeUpdating {
            get {
                return ResourceManager.GetString("StopProgramOnAllComputersBeforeUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplies.
        /// </summary>
        public static string Supplies {
            get {
                return ResourceManager.GetString("Supplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplies Needed.
        /// </summary>
        public static string SuppliesNeeded {
            get {
                return ResourceManager.GetString("SuppliesNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply.
        /// </summary>
        public static string Supply {
            get {
                return ResourceManager.GetString("Supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply List.
        /// </summary>
        public static string SupplyList {
            get {
                return ResourceManager.GetString("SupplyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply list is empty..
        /// </summary>
        public static string SupplyListEmpty {
            get {
                return ResourceManager.GetString("SupplyListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Needed.
        /// </summary>
        public static string SupplyNeeded {
            get {
                return ResourceManager.GetString("SupplyNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Order.
        /// </summary>
        public static string SupplyOrder {
            get {
                return ResourceManager.GetString("SupplyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Order Item.
        /// </summary>
        public static string SupplyOrderItem {
            get {
                return ResourceManager.GetString("SupplyOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Orders.
        /// </summary>
        public static string SupplyOrders {
            get {
                return ResourceManager.GetString("SupplyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the subject and body of the template cannot be left blank..
        /// </summary>
        public static string TemplateSubjectAndBodyCannotBeLeftBlank {
            get {
                return ResourceManager.GetString("TemplateSubjectAndBodyCannotBeLeftBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates available. You are using the most current version..
        /// </summary>
        public static string ThereAreNoUpdatesAvailable {
            get {
                return ResourceManager.GetString("ThereAreNoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a pending order for this supplier. Please finish this order in the orders window..
        /// </summary>
        public static string ThereIsAPendingOrderForThisSupplier {
            get {
                return ResourceManager.GetString("ThereIsAPendingOrderForThisSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem launching {0}.
        /// </summary>
        public static string ThereWasAProblemLaunchingFile {
            get {
                return ResourceManager.GetString("ThereWasAProblemLaunchingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Est Value.
        /// </summary>
        public static string TotalEstValue {
            get {
                return ResourceManager.GetString("TotalEstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to connect to web service.......
        /// </summary>
        public static string UpdateAttemptingToConnectWebService {
            get {
                return ResourceManager.GetString("UpdateAttemptingToConnectWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a update is available..
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update is available for download. Would you like to update now?.
        /// </summary>
        public static string UpdateAvailableInstallNow {
            get {
                return ResourceManager.GetString("UpdateAvailableInstallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to install updates..
        /// </summary>
        public static string UpdateNotAuthorized {
            get {
                return ResourceManager.GetString("UpdateNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Setup.
        /// </summary>
        public static string UpdateSetup {
            get {
                return ResourceManager.GetString("UpdateSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates are not allowed on this replication server..
        /// </summary>
        public static string UpdatesNotAllowedOnReplicationServer {
            get {
                return ResourceManager.GetString("UpdatesNotAllowedOnReplicationServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User mail address cannot be set as the default..
        /// </summary>
        public static string UserMailAddressCannotBeSetAsDefault {
            get {
                return ResourceManager.GetString("UserMailAddressCannotBeSetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown&gt;.
        /// </summary>
        public static string UserUnknown {
            get {
                return ResourceManager.GetString("UserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using version {0}.
        /// </summary>
        public static string UsingVersion {
            get {
                return ResourceManager.GetString("UsingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using version {0} since {1}.
        /// </summary>
        public static string UsingVersionSince {
            get {
                return ResourceManager.GetString("UsingVersionSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive this wiki page? It will still be available from the Search window if needed..
        /// </summary>
        public static string WikiArchiveWikiPageConfirm {
            get {
                return ResourceManager.GetString("WikiArchiveWikiPageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot archive homepage..
        /// </summary>
        public static string WikiCannotArchiveHomepage {
            get {
                return ResourceManager.GetString("WikiCannotArchiveHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename the default homepage..
        /// </summary>
        public static string WikiCannotRenameTheDefaultHomepage {
            get {
                return ResourceManager.GetString("WikiCannotRenameTheDefaultHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column names cannot contain spaces..
        /// </summary>
        public static string WikiColumnCannotContainSpaces {
            get {
                return ResourceManager.GetString("WikiColumnCannotContainSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column names cannot contain special characters..
        /// </summary>
        public static string WikiColumnCannotContainSpecialCharacters {
            get {
                return ResourceManager.GetString("WikiColumnCannotContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column cannot start with numbers..
        /// </summary>
        public static string WikiColumnCannotStartWithNumbers {
            get {
                return ResourceManager.GetString("WikiColumnCannotStartWithNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name &apos;{0}&apos; is a reserved word in MySQL..
        /// </summary>
        public static string WikiColumnName0IsReservedWord {
            get {
                return ResourceManager.GetString("WikiColumnName0IsReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name is a reserved word in MySQL..
        /// </summary>
        public static string WikiColumnNameIsReservedWord {
            get {
                return ResourceManager.GetString("WikiColumnNameIsReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column widths must only contain positive integers..
        /// </summary>
        public static string WikiColumnWidthsMustOnlyContainPositiveIntegers {
            get {
                return ResourceManager.GetString("WikiColumnWidthsMustOnlyContainPositiveIntegers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this draft?.
        /// </summary>
        public static string WikiDeleteDraft {
            get {
                return ResourceManager.GetString("WikiDeleteDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this list item and all references to it?.
        /// </summary>
        public static string WikiDeleteItemAndReferences {
            get {
                return ResourceManager.GetString("WikiDeleteItemAndReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Drafts.
        /// </summary>
        public static string WikiDrafts {
            get {
                return ResourceManager.GetString("WikiDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate column name detected.
        /// </summary>
        public static string WikiDuplicateColumnNameDetected {
            get {
                return ResourceManager.GetString("WikiDuplicateColumnNameDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit List Item.
        /// </summary>
        public static string WikiEditListItem {
            get {
                return ResourceManager.GetString("WikiEditListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Wiki List Headers.
        /// </summary>
        public static string WikiEditWikiListHeaders {
            get {
                return ResourceManager.GetString("WikiEditWikiListHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Wiki List Item.
        /// </summary>
        public static string WikiEditWikiListItem {
            get {
                return ResourceManager.GetString("WikiEditWikiListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist. Continue anyway?.
        /// </summary>
        public static string WikiFileDoesNotExistContinueAnyway {
            get {
                return ResourceManager.GetString("WikiFileDoesNotExistContinueAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist. Continue anyway?.
        /// </summary>
        public static string WikiFolderDoesNotExistContinueAnyway {
            get {
                return ResourceManager.GetString("WikiFolderDoesNotExistContinueAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki History.
        /// </summary>
        public static string WikiHistory {
            get {
                return ResourceManager.GetString("WikiHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Links.
        /// </summary>
        public static string WikiIncomingLinks {
            get {
                return ResourceManager.GetString("WikiIncomingLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming links to {0}.
        /// </summary>
        public static string WikiIncomingLinksTo0 {
            get {
                return ResourceManager.GetString("WikiIncomingLinksTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert File Link.
        /// </summary>
        public static string WikiInsertFileLink {
            get {
                return ResourceManager.GetString("WikiInsertFileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Folder Link.
        /// </summary>
        public static string WikiInsertFolderLink {
            get {
                return ResourceManager.GetString("WikiInsertFolderLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List already exists with that name. Would you like to edit existing list?.
        /// </summary>
        public static string WikiListAlreadyExistsWithThatName {
            get {
                return ResourceManager.GetString("WikiListAlreadyExistsWithThatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List name cannot be blank..
        /// </summary>
        public static string WikiListNameCannotBeBlank {
            get {
                return ResourceManager.GetString("WikiListNameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List name is a reserved word in MySQL..
        /// </summary>
        public static string WikiListNameIsReservedWord {
            get {
                return ResourceManager.GetString("WikiListNameIsReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Lists.
        /// </summary>
        public static string WikiLists {
            get {
                return ResourceManager.GetString("WikiLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New List Name.
        /// </summary>
        public static string WikiNewListName {
            get {
                return ResourceManager.GetString("WikiNewListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Pick List Option.
        /// </summary>
        public static string WIkiNewPickListOption {
            get {
                return ResourceManager.GetString("WIkiNewPickListOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That page does not exist. Would you like to create it?.
        /// </summary>
        public static string WikiPageDoesNotExist {
            get {
                return ResourceManager.GetString("WikiPageDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That page does not exist and cannot be made because the page title contains invalid characters..
        /// </summary>
        public static string WikiPageDoesNotExistAndTitleInvalid {
            get {
                return ResourceManager.GetString("WikiPageDoesNotExistAndTitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page has no incoming links..
        /// </summary>
        public static string WikiPageHasNoIncomingLinks {
            get {
                return ResourceManager.GetString("WikiPageHasNoIncomingLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page has one or more drafts associated with it. Would you like to open a draft instead of the current Wiki page?.
        /// </summary>
        public static string WikiPageHasOneOrMoreDrafts {
            get {
                return ResourceManager.GetString("WikiPageHasOneOrMoreDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is broken and cannot be viewed..
        /// </summary>
        public static string WikiPageIsBroken {
            get {
                return ResourceManager.GetString("WikiPageIsBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        public static string WikiPageTitle {
            get {
                return ResourceManager.GetString("WikiPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page title already exists..
        /// </summary>
        public static string WikiPageTitleAlreadyExists {
            get {
                return ResourceManager.GetString("WikiPageTitleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page title cannot be empty..
        /// </summary>
        public static string WikiPageTitleCannotBeEmpty {
            get {
                return ResourceManager.GetString("WikiPageTitleCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert page to currently selected revision?.
        /// </summary>
        public static string WikiRevertPageToSelectedRevision {
            get {
                return ResourceManager.GetString("WikiRevertPageToSelectedRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Search.
        /// </summary>
        public static string WikiSearch {
            get {
                return ResourceManager.GetString("WikiSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected page has already been restored..
        /// </summary>
        public static string WikiSelectedPageAlreadyRestored {
            get {
                return ResourceManager.GetString("WikiSelectedPageAlreadyRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation &apos;{0}&apos; is still updating.  Please wait and &apos;Try Again&apos;.
        /// </summary>
        public static string WorkstationIsStillUpdating {
            get {
                return ResourceManager.GetString("WorkstationIsStillUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must change your password to a strong password due to the current Security settings..
        /// </summary>
        public static string YouMustChangeYourPasswordToAStrongPassword {
            get {
                return ResourceManager.GetString("YouMustChangeYourPasswordToAStrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an email before replying..
        /// </summary>
        public static string YouMustSelectAnEmailBeforeReplying {
            get {
                return ResourceManager.GetString("YouMustSelectAnEmailBeforeReplying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an email to forward..
        /// </summary>
        public static string YouMustSelectAnEmailToForward {
            get {
                return ResourceManager.GetString("YouMustSelectAnEmailToForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a valid day..
        /// </summary>
        public static string YouMustSpecifyAValidDay {
            get {
                return ResourceManager.GetString("YouMustSpecifyAValidDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be allowed access when you restart..
        /// </summary>
        public static string YouWillBeAllowedAccessWhenYouRestart {
            get {
                return ResourceManager.GetString("YouWillBeAllowedAccessWhenYouRestart", resourceCulture);
            }
        }
    }
}
