//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDental.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenDental.Translation.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy.
        /// </summary>
        public static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this allergy?.
        /// </summary>
        public static string AllergyConfirmDelete {
            get {
                return ResourceManager.GetString("AllergyConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy Definition.
        /// </summary>
        public static string AllergyDef {
            get {
                return ResourceManager.GetString("AllergyDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete allergies in use..
        /// </summary>
        public static string AllergyDefCannotDeleteInUse {
            get {
                return ResourceManager.GetString("AllergyDefCannotDeleteInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this allergy definition?.
        /// </summary>
        public static string AllergyDefConfirmDelete {
            get {
                return ResourceManager.GetString("AllergyDefConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one code is allowed per allergy def..
        /// </summary>
        public static string AllergyOnlyOneUniiCodePerAllergyAllowed {
            get {
                return ResourceManager.GetString("AllergyOnlyOneUniiCodePerAllergyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one allergy..
        /// </summary>
        public static string AllergySelectAtLeastOne {
            get {
                return ResourceManager.GetString("AllergySelectAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy Setup.
        /// </summary>
        public static string AllergySetup {
            get {
                return ResourceManager.GetString("AllergySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNII code contains invalid characters: {0}.
        /// </summary>
        public static string AllergyUniiCodeContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("AllergyUniiCodeContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNII code must be 10 characters in length..
        /// </summary>
        public static string AllergyUniiCodeMustBe10Characters {
            get {
                return ResourceManager.GetString("AllergyUniiCodeMustBe10Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is in progress on workstation &apos;{0}&apos;.
        ///
        ///Not allowed to start Softlex while an update is in progress.
        ///Please wait and click &apos;Try Again&apos;..
        /// </summary>
        public static string AnUpdateIsInProgressOnWorkstation {
            get {
                return ResourceManager.GetString("AnUpdateIsInProgressOnWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are the person who started the update and you wish to override this message because an update is not in progress, click &apos;Override&apos;..
        /// </summary>
        public static string ClickOverrideToOverrideUpdateMessage {
            get {
                return ResourceManager.GetString("ClickOverrideToOverrideUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string ColumnColumn {
            get {
                return ResourceManager.GetString("ColumnColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        public static string ColumnColumnName {
            get {
                return ResourceManager.GetString("ColumnColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        public static string ColumnDateTime {
            get {
                return ResourceManager.GetString("ColumnDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        public static string ColumnDel {
            get {
                return ResourceManager.GetString("ColumnDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text.
        /// </summary>
        public static string ColumnInputText {
            get {
                return ResourceManager.GetString("ColumnInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Text.
        /// </summary>
        public static string ColumnLogText {
            get {
                return ResourceManager.GetString("ColumnLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        public static string ColumnPageTitle {
            get {
                return ResourceManager.GetString("ColumnPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string ColumnPermission {
            get {
                return ResourceManager.GetString("ColumnPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string ColumnSaved {
            get {
                return ResourceManager.GetString("ColumnSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ColumnTitle {
            get {
                return ResourceManager.GetString("ColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ColumnUser {
            get {
                return ResourceManager.GetString("ColumnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ColumnValue {
            get {
                return ResourceManager.GetString("ColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ColumnWidth {
            get {
                return ResourceManager.GetString("ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful..
        /// </summary>
        public static string ConnectionSuccessful {
            get {
                return ResourceManager.GetString("ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password incorrect..
        /// </summary>
        public static string CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be blank..
        /// </summary>
        public static string DescriptionCannotBeBlank {
            get {
                return ResourceManager.GetString("DescriptionCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show me this message again..
        /// </summary>
        public static string DoNotShowThisMessageAgain {
            get {
                return ResourceManager.GetString("DoNotShowThisMessageAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a valid date..
        /// </summary>
        public static string EnterAValidDate {
            get {
                return ResourceManager.GetString("EnterAValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter or select a valid time..
        /// </summary>
        public static string EnterOrSelectAValidDate {
            get {
                return ResourceManager.GetString("EnterOrSelectAValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates..
        /// </summary>
        public static string ErrorCheckingForUpdates {
            get {
                return ResourceManager.GetString("ErrorCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registration key..
        /// </summary>
        public static string InvalidRegistrationKey {
            get {
                return ResourceManager.GetString("InvalidRegistrationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registration key format..
        /// </summary>
        public static string InvalidRegistrationKeyFormat {
            get {
                return ResourceManager.GetString("InvalidRegistrationKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string lang_create_password {
            get {
                return ResourceManager.GetString("lang_create_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Saved.
        /// </summary>
        public static string lang_last_saved {
            get {
                return ResourceManager.GetString("lang_last_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string lang_login_failed {
            get {
                return ResourceManager.GetString("lang_login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string lang_new_password {
            get {
                return ResourceManager.GetString("lang_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Enter Password.
        /// </summary>
        public static string lang_re_enter_password {
            get {
                return ResourceManager.GetString("lang_re_enter_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string lang_user {
            get {
                return ResourceManager.GetString("lang_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has logged on.
        /// </summary>
        public static string lang_user_has_logged_on {
            get {
                return ResourceManager.GetString("lang_user_has_logged_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must change your password to a strong password due to the current Security settings..
        /// </summary>
        public static string lang_you_must_change_password_to_stronger_password {
            get {
                return ResourceManager.GetString("lang_you_must_change_password_to_stronger_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to log off?.
        /// </summary>
        public static string LogOffConfirmation {
            get {
                return ResourceManager.GetString("LogOffConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dental.
        /// </summary>
        public static string OpenDental {
            get {
                return ResourceManager.GetString("OpenDental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match and not be empty..
        /// </summary>
        public static string PasswordsMustMatchAndNotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordsMustMatchAndNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Time.
        /// </summary>
        public static string PickTime {
            get {
                return ResourceManager.GetString("PickTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem refreshing the Audit Trail with the current filters..
        /// </summary>
        public static string ProblemRefreshingAuditTrail {
            get {
                return ResourceManager.GetString("ProblemRefreshingAuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Key.
        /// </summary>
        public static string RegistrationKey {
            get {
                return ResourceManager.GetString("RegistrationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be sure to stop the program on all other computers in the office before installing..
        /// </summary>
        public static string StopProgramOnAllComputersBeforeUpdating {
            get {
                return ResourceManager.GetString("StopProgramOnAllComputersBeforeUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates available. You are using the most current version..
        /// </summary>
        public static string ThereAreNoUpdatesAvailable {
            get {
                return ResourceManager.GetString("ThereAreNoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem launching {0}.
        /// </summary>
        public static string ThereWasAProblemLaunchingFile {
            get {
                return ResourceManager.GetString("ThereWasAProblemLaunchingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to connect to web service.......
        /// </summary>
        public static string UpdateAttemptingToConnectWebService {
            get {
                return ResourceManager.GetString("UpdateAttemptingToConnectWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a update is available..
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update is available for download. Would you like to update now?.
        /// </summary>
        public static string UpdateAvailableInstallNow {
            get {
                return ResourceManager.GetString("UpdateAvailableInstallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to install updates..
        /// </summary>
        public static string UpdateNotAuthorized {
            get {
                return ResourceManager.GetString("UpdateNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Setup.
        /// </summary>
        public static string UpdateSetup {
            get {
                return ResourceManager.GetString("UpdateSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates are not allowed on this replication server..
        /// </summary>
        public static string UpdatesNotAllowedOnReplicationServer {
            get {
                return ResourceManager.GetString("UpdatesNotAllowedOnReplicationServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown&gt;.
        /// </summary>
        public static string UserUnknown {
            get {
                return ResourceManager.GetString("UserUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the CEMT tool to change your password..
        /// </summary>
        public static string UseTheCEMTToolToChangeYourPassword {
            get {
                return ResourceManager.GetString("UseTheCEMTToolToChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using version {0}.
        /// </summary>
        public static string UsingVersion {
            get {
                return ResourceManager.GetString("UsingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using version {0} since {1}.
        /// </summary>
        public static string UsingVersionSince {
            get {
                return ResourceManager.GetString("UsingVersionSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive this wiki page? It will still be available from the Search window if needed..
        /// </summary>
        public static string WikiArchiveWikiPageConfirm {
            get {
                return ResourceManager.GetString("WikiArchiveWikiPageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot archive homepage..
        /// </summary>
        public static string WikiCannotArchiveHomepage {
            get {
                return ResourceManager.GetString("WikiCannotArchiveHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename the default homepage..
        /// </summary>
        public static string WikiCannotRenameTheDefaultHomepage {
            get {
                return ResourceManager.GetString("WikiCannotRenameTheDefaultHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column names cannot contain spaces..
        /// </summary>
        public static string WikiColumnCannotContainSpaces {
            get {
                return ResourceManager.GetString("WikiColumnCannotContainSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column names cannot contain special characters..
        /// </summary>
        public static string WikiColumnCannotContainSpecialCharacters {
            get {
                return ResourceManager.GetString("WikiColumnCannotContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column cannot start with numbers..
        /// </summary>
        public static string WikiColumnCannotStartWithNumbers {
            get {
                return ResourceManager.GetString("WikiColumnCannotStartWithNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name &apos;{0}&apos; is a reserved word in MySQL..
        /// </summary>
        public static string WikiColumnName0IsReservedWord {
            get {
                return ResourceManager.GetString("WikiColumnName0IsReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name is a reserved word in MySQL..
        /// </summary>
        public static string WikiColumnNameIsReservedWord {
            get {
                return ResourceManager.GetString("WikiColumnNameIsReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column widths must only contain positive integers..
        /// </summary>
        public static string WikiColumnWidthsMustOnlyContainPositiveIntegers {
            get {
                return ResourceManager.GetString("WikiColumnWidthsMustOnlyContainPositiveIntegers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this draft?.
        /// </summary>
        public static string WikiDeleteDraft {
            get {
                return ResourceManager.GetString("WikiDeleteDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this list item and all references to it?.
        /// </summary>
        public static string WikiDeleteItemAndReferences {
            get {
                return ResourceManager.GetString("WikiDeleteItemAndReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Drafts.
        /// </summary>
        public static string WikiDrafts {
            get {
                return ResourceManager.GetString("WikiDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate column name detected.
        /// </summary>
        public static string WikiDuplicateColumnNameDetected {
            get {
                return ResourceManager.GetString("WikiDuplicateColumnNameDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit List Item.
        /// </summary>
        public static string WikiEditListItem {
            get {
                return ResourceManager.GetString("WikiEditListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Wiki List Headers.
        /// </summary>
        public static string WikiEditWikiListHeaders {
            get {
                return ResourceManager.GetString("WikiEditWikiListHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Wiki List Item.
        /// </summary>
        public static string WikiEditWikiListItem {
            get {
                return ResourceManager.GetString("WikiEditWikiListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist. Continue anyway?.
        /// </summary>
        public static string WikiFileDoesNotExistContinueAnyway {
            get {
                return ResourceManager.GetString("WikiFileDoesNotExistContinueAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist. Continue anyway?.
        /// </summary>
        public static string WikiFolderDoesNotExistContinueAnyway {
            get {
                return ResourceManager.GetString("WikiFolderDoesNotExistContinueAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki History.
        /// </summary>
        public static string WikiHistory {
            get {
                return ResourceManager.GetString("WikiHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Links.
        /// </summary>
        public static string WikiIncomingLinks {
            get {
                return ResourceManager.GetString("WikiIncomingLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming links to {0}.
        /// </summary>
        public static string WikiIncomingLinksTo0 {
            get {
                return ResourceManager.GetString("WikiIncomingLinksTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert File Link.
        /// </summary>
        public static string WikiInsertFileLink {
            get {
                return ResourceManager.GetString("WikiInsertFileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Folder Link.
        /// </summary>
        public static string WikiInsertFolderLink {
            get {
                return ResourceManager.GetString("WikiInsertFolderLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List already exists with that name. Would you like to edit existing list?.
        /// </summary>
        public static string WikiListAlreadyExistsWithThatName {
            get {
                return ResourceManager.GetString("WikiListAlreadyExistsWithThatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List name cannot be blank..
        /// </summary>
        public static string WikiListNameCannotBeBlank {
            get {
                return ResourceManager.GetString("WikiListNameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List name is a reserved word in MySQL..
        /// </summary>
        public static string WikiListNameIsReservedWord {
            get {
                return ResourceManager.GetString("WikiListNameIsReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Lists.
        /// </summary>
        public static string WikiLists {
            get {
                return ResourceManager.GetString("WikiLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New List Name.
        /// </summary>
        public static string WikiNewListName {
            get {
                return ResourceManager.GetString("WikiNewListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Pick List Option.
        /// </summary>
        public static string WIkiNewPickListOption {
            get {
                return ResourceManager.GetString("WIkiNewPickListOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That page does not exist. Would you like to create it?.
        /// </summary>
        public static string WikiPageDoesNotExist {
            get {
                return ResourceManager.GetString("WikiPageDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That page does not exist and cannot be made because the page title contains invalid characters..
        /// </summary>
        public static string WikiPageDoesNotExistAndTitleInvalid {
            get {
                return ResourceManager.GetString("WikiPageDoesNotExistAndTitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page has no incoming links..
        /// </summary>
        public static string WikiPageHasNoIncomingLinks {
            get {
                return ResourceManager.GetString("WikiPageHasNoIncomingLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page has one or more drafts associated with it. Would you like to open a draft instead of the current Wiki page?.
        /// </summary>
        public static string WikiPageHasOneOrMoreDrafts {
            get {
                return ResourceManager.GetString("WikiPageHasOneOrMoreDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is broken and cannot be viewed..
        /// </summary>
        public static string WikiPageIsBroken {
            get {
                return ResourceManager.GetString("WikiPageIsBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        public static string WikiPageTitle {
            get {
                return ResourceManager.GetString("WikiPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page title already exists..
        /// </summary>
        public static string WikiPageTitleAlreadyExists {
            get {
                return ResourceManager.GetString("WikiPageTitleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page title cannot be empty..
        /// </summary>
        public static string WikiPageTitleCannotBeEmpty {
            get {
                return ResourceManager.GetString("WikiPageTitleCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert page to currently selected revision?.
        /// </summary>
        public static string WikiRevertPageToSelectedRevision {
            get {
                return ResourceManager.GetString("WikiRevertPageToSelectedRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Search.
        /// </summary>
        public static string WikiSearch {
            get {
                return ResourceManager.GetString("WikiSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected page has already been restored..
        /// </summary>
        public static string WikiSelectedPageAlreadyRestored {
            get {
                return ResourceManager.GetString("WikiSelectedPageAlreadyRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation &apos;{0}&apos; is still updating.  Please wait and &apos;Try Again&apos;.
        /// </summary>
        public static string WorkstationIsStillUpdating {
            get {
                return ResourceManager.GetString("WorkstationIsStillUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be allowed access when you restart..
        /// </summary>
        public static string YouWillBeAllowedAccessWhenYouRestart {
            get {
                return ResourceManager.GetString("YouWillBeAllowedAccessWhenYouRestart", resourceCulture);
            }
        }
    }
}
