//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDental.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageSecurity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageSecurity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenDental.Translation.LanguageSecurity", typeof(LanguageSecurity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions accessed.
        /// </summary>
        public static string DefinitionsAccessed {
            get {
                return ResourceManager.GetString("DefinitionsAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment list printed.
        /// </summary>
        public static string EquipmentListPrinted {
            get {
                return ResourceManager.GetString("EquipmentListPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added.
        /// </summary>
        public static string GenericItemAdded {
            get {
                return ResourceManager.GetString("GenericItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted.
        /// </summary>
        public static string GenericItemDeleted {
            get {
                return ResourceManager.GetString("GenericItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} edited.
        /// </summary>
        public static string GenericItemModified {
            get {
                return ResourceManager.GetString("GenericItemModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplies needed list printed.
        /// </summary>
        public static string SuppliesNeededListPrinted {
            get {
                return ResourceManager.GetString("SuppliesNeededListPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplies order from {0} printed.
        /// </summary>
        public static string SuppliesOrderFromDatePrinted {
            get {
                return ResourceManager.GetString("SuppliesOrderFromDatePrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Setup window accesssed.
        /// </summary>
        public static string UpdateSetupWindowAccessed {
            get {
                return ResourceManager.GetString("UpdateSetupWindowAccessed", resourceCulture);
            }
        }
    }
}
