//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateFileCopier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateFileCopier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up....
        /// </summary>
        internal static string LangCleaningUp {
            get {
                return ResourceManager.GetString("LangCleaningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string LangDone {
            get {
                return ResourceManager.GetString("LangDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to Copy Files....
        /// </summary>
        internal static string LangPreparingToCopyFiles {
            get {
                return ResourceManager.GetString("LangPreparingToCopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files failed to copy. Verify network access and permissions are correct, then click Retry..
        /// </summary>
        internal static string LangSomeFilesFailedToCopy {
            get {
                return ResourceManager.GetString("LangSomeFilesFailedToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up: {0}.
        /// </summary>
        internal static string LangStatusBackingUp {
            get {
                return ResourceManager.GetString("LangStatusBackingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying: {0}.
        /// </summary>
        internal static string LangStatusCopying {
            get {
                return ResourceManager.GetString("LangStatusCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverting: {0}.
        /// </summary>
        internal static string LangStatusReverting {
            get {
                return ResourceManager.GetString("LangStatusReverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are files still in use. Please make sure all instances of Imedisoft are closed then click Retry..
        /// </summary>
        internal static string LangThereAreFilesInUse {
            get {
                return ResourceManager.GetString("LangThereAreFilesInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access {0}..
        /// </summary>
        internal static string LangUnableToAccess {
            get {
                return ResourceManager.GetString("LangUnableToAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update File Copier.
        /// </summary>
        internal static string LangUpdateFileCopier {
            get {
                return ResourceManager.GetString("LangUpdateFileCopier", resourceCulture);
            }
        }
    }
}
