using System;

namespace OpenDentBusiness
{
    /// <summary>
    /// This enum is stored in the database as strings rather than as numbers, so we can do the 
    /// order alphabetically and we can change it whenever we want.
    /// </summary>
    public enum ProgramName
    {
        None,
        ActeonImagingSuite,
        Adstra,
        Apixia,
        Apteryx,
        AudaxCeph,
        ///<summary>Avalara Inc.</summary>
        AvaTax,
        BioPAK,
        ///<summary>Newer version of MediaDent. Uses OLE COM interface.</summary>
        CADI,
        CallFire,
        Camsight,
        CaptureLink,
        Carestream,
        CentralDataStorage,
        Cerec,
        CleaRay,
        CliniView,
        ClioSoft,
        DBSWin,
        DemandForce,
        DentalEye,
        DentalIntel,
        DentalStudio,
        DentalTekSmartOfficePhone,
        DentForms,
        DentX,
        Dexis,
        Digora,
        Dimaxis,
        Divvy,
        Dolphin,
        DrCeph,
        Dropbox,
        DXCPatientCreditScore,
        Dxis,
        EasyNotesPro,
        eClinicalWorks,
        ///<summary>electronic Rx.</summary>
        eRx,
        EvaSoft,
        EwooEZDent,
        FHIR,
        FloridaProbe,
        Guru,
        HandyDentist,
        HdxWill,
        HouseCalls,
        IAP,
        iCat,
        iDixel,
        ImageFX,
        iRYS,
        Lightyear,
        MediaDent,
        Midway,
        MiPACS,
        Mountainside,
        NewTomNNT,
        Office,
        ///<summary>Please use Programs.UsingOrion where possible.</summary>
        Orion,
        OrthoCAD,
        OrthoInsight3d,
        OrthoPlex,
        Oryx,
        Owandy,
        PandaPerio,
        PandaPeriodAdvanced,
        [Obsolete] PayConnect,
        [Obsolete] PaySimple,
        Patterson,
        PerioPal,
        Podium,
        PracticeByNumbers,
        PracticeWebReports,
        Progeny,
        PT,
        PTupdate,
        RapidCall,
        RayMage,
        Romexis,
        Scanora,
        Schick,
        SFTP,
        Sirona,
        SMARTDent,
        Sopro,
        TigerView,
        Transworld,
        Triana,
        Trojan,
        Trophy,
        TrophyEnhanced,
        Tscan,
        UAppoint,
        Vipersoft,
        visOra,
        VistaDent,
        VixWin,
        VixWinBase36,
        VixWinBase41,
        VixWinNumbered,
        VixWinOld,
        [Obsolete] Xcharge,
        XDR,
        XVWeb,
        ZImage
    }
}
